/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sdegaonk' at '2/24/17 4:08 PM' with Gradle 2.14.1
 *
 * @author sdegaonk, @date 2/24/17 4:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
